<?php
/**
 *
 * @author Antoine Ouellette
 */
?>
<!DOCTYPE html>
<html lang="fr-CA">

<head>
    <title><?php echo $_SESSION['TAB_TITLE']?> - Vitrine informatique</title>
    <meta charset="utf-8">
    <meta name="description" content="<?php echo $_SESSION['PAGE_DESCRIPTION']?>">
    <meta name="author" content="Antoine Ouellette">

    <link rel="icon" href="favicon.ico" type="image/png"/>
    <link rel="stylesheet" href="css/styles.css">

</head>